import type { StoreData } from "./types";

function daysAgo(n: number) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function dateOffset(n: number) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toLocaleDateString("en-CA", { timeZone: "America/New_York" });
}

export function seedStore(): StoreData {
  return {
    services: [
      {
        id: "svc-box-braids",
        slug: "box-braids",
        name: "Box Braids",
        tagline: "The timeless classic, refined.",
        description:
          "Clean, sculpted box braids with a glossy finish and lasting shape — from bob to waist length.",
        longDescription:
          "Our signature box braids are parted with precision and finished for movement, shine, and scalp comfort. Choose your length, size, and color story. We use premium extensions and a tension-aware technique so your style looks editorial on day one and still beautiful weeks later.",
        priceFrom: 180,
        durationMin: 240,
        durationMax: 480,
        image: "/images/style-box-braids.jpg",
        featured: true,
        category: "braids",
      },
      {
        id: "svc-knotless",
        slug: "knotless-braids",
        name: "Knotless Braids",
        tagline: "Weightless luxury at the root.",
        description:
          "Seamless knotless braids that protect the hairline and feel light from the first hour.",
        longDescription:
          "Knotless braiding is our most requested service for a reason: a flatter, more natural start, less tension, and a refined silhouette. Ideal for clients who want a premium look with everyday comfort. We customize size, length, and curl-end options including boho and goddess finishes.",
        priceFrom: 220,
        durationMin: 300,
        durationMax: 540,
        image: "/images/style-knotless.jpg",
        featured: true,
        category: "knotless",
      },
      {
        id: "svc-cornrows",
        slug: "cornrows",
        name: "Cornrows",
        tagline: "Geometry, culture, precision.",
        description:
          "Straight-back, feed-in, and designer cornrow patterns with museum-level parting.",
        longDescription:
          "From classic straight-backs to intricate designer maps, our cornrows honor African braiding traditions with a contemporary, fashion-forward finish. Feed-in technique keeps edges soft. Perfect as a standalone look or as a foundation for wigs and updos.",
        priceFrom: 85,
        durationMin: 90,
        durationMax: 240,
        image: "/images/style-cornrows.jpg",
        featured: true,
        category: "cornrows",
      },
      {
        id: "svc-twists",
        slug: "senegalese-twists",
        name: "Senegalese Twists",
        tagline: "Sculpted ropes of movement.",
        description:
          "Polished Senegalese and rope twists with a soft, luxurious drape.",
        longDescription:
          "Twists are our love letter to texture and rhythm. We create even, luminous Senegalese twists that swing with every step. Choose marley, kinky, or silky finishes. A sophisticated alternative to braids with equally lasting results.",
        priceFrom: 190,
        durationMin: 240,
        durationMax: 480,
        image: "/images/style-twists.jpg",
        featured: true,
        category: "twists",
      },
      {
        id: "svc-fulani",
        slug: "fulani-braids",
        name: "Fulani Braids",
        tagline: "Heritage, adorned.",
        description:
          "Center-part Fulani silhouettes with gold beads, cuffs, and ceremonial detail.",
        longDescription:
          "Fulani braids are designed as jewelry for the hair — a center part, face-framing braids, and optional gold beads or cowrie accents. We keep the look regal, never costume. Ideal for celebrations, editorials, and everyday distinction.",
        priceFrom: 210,
        durationMin: 240,
        durationMax: 420,
        image: "/images/style-fulani.jpg",
        featured: true,
        category: "special",
      },
      {
        id: "svc-goddess",
        slug: "goddess-braids",
        name: "Goddess Braids",
        tagline: "Soft power. Curled ends.",
        description:
          "Elevated goddess and boho braids with romantic curl, volume, and movement.",
        longDescription:
          "Goddess braids combine the structure of knotless braiding with loose, curly ends for a romantic, high-fashion finish. We blend human-hair curl pieces for a lived-in luxury that photographs beautifully and feels effortless.",
        priceFrom: 240,
        durationMin: 300,
        durationMax: 540,
        image: "/images/style-goddess.jpg",
        featured: true,
        category: "special",
      },
      {
        id: "svc-kids",
        slug: "kids-braids",
        name: "Kids Braids",
        tagline: "Gentle hands. Lasting styles.",
        description:
          "Comfort-first braids, cornrows, and beads for children in a calm, kind studio.",
        longDescription:
          "Little clients receive extra time, extra patience, and tension-aware styling. We specialize in kids’ cornrows, box braids, and beadwork that stay neat for school, dance, and weekends. Parents stay welcome in the suite.",
        priceFrom: 80,
        durationMin: 90,
        durationMax: 240,
        image: "/images/style-kids.jpg",
        featured: true,
        category: "kids",
      },
      {
        id: "svc-extensions",
        slug: "hair-extensions",
        name: "Hair Extensions",
        tagline: "Length, color, and density — tailored.",
        description:
          "Premium braiding hair and extension blending, matched to your texture and vision.",
        longDescription:
          "We source and blend premium kanekalon, pre-stretched, and human-hair pieces so your finished style has the right weight, sheen, and color dimension. Consultation included with every braiding appointment — or book a standalone extension consult.",
        priceFrom: 45,
        durationMin: 30,
        durationMax: 90,
        image: "/images/style-extensions.jpg",
        featured: false,
        category: "braids",
      },
      {
        id: "svc-wig",
        slug: "wig-installation",
        name: "Wig Installation",
        tagline: "Invisible hairline. Secure wear.",
        description:
          "Professional wig install, pluck, and melt over a braided foundation.",
        longDescription:
          "A clean braided base, precise placement, and a melted hairline that looks like your own. We install, customize, and style closures, frontals, and glueless units with a focus on scalp health and all-day comfort.",
        priceFrom: 95,
        durationMin: 90,
        durationMax: 180,
        image: "/images/style-wig.jpg",
        featured: false,
        category: "special",
      },
      {
        id: "svc-natural",
        slug: "natural-hair-care",
        name: "Natural Hair Care",
        tagline: "Health before style.",
        description:
          "Cleansing, steam, deep condition, and trim rituals for textured hair.",
        longDescription:
          "Before every masterpiece, the canvas. Our natural hair care menu includes clarifying, botanical steam, protein-moisture balancing, and precision trims. Recommended before long-term protective styles and as a reset between installs.",
        priceFrom: 75,
        durationMin: 60,
        durationMax: 120,
        image: "/images/style-natural.jpg",
        featured: false,
        category: "special",
      },
    ],
    styles: [
      {
        id: "stl-classic-box",
        slug: "classic-box-braids",
        name: "Classic Medium Box Braids",
        description: "Clean medium parts, hip length, a polished everyday icon.",
        category: "braids",
        serviceId: "svc-box-braids",
        image: "/images/style-box-braids.jpg",
        durationMin: 300,
        durationMax: 420,
        priceFrom: 220,
        featured: true,
      },
      {
        id: "stl-small-knotless",
        slug: "small-knotless",
        name: "Small Knotless Braids",
        description: "Fine, weightless knotless braids with a silk-like fall.",
        category: "knotless",
        serviceId: "svc-knotless",
        image: "/images/style-knotless.jpg",
        durationMin: 420,
        durationMax: 540,
        priceFrom: 320,
        featured: true,
      },
      {
        id: "stl-jumbo-knotless",
        slug: "jumbo-knotless",
        name: "Jumbo Knotless",
        description: "Sculptural jumbo knotless with dramatic movement.",
        category: "knotless",
        serviceId: "svc-knotless",
        image: "/images/gallery-02.jpg",
        durationMin: 240,
        durationMax: 360,
        priceFrom: 200,
        featured: true,
      },
      {
        id: "stl-designer-cornrows",
        slug: "designer-cornrows",
        name: "Designer Cornrows",
        description: "Geometric feed-in maps with a contemporary edge.",
        category: "cornrows",
        serviceId: "svc-cornrows",
        image: "/images/style-cornrows.jpg",
        durationMin: 150,
        durationMax: 240,
        priceFrom: 140,
        featured: true,
      },
      {
        id: "stl-senegalese",
        slug: "luminous-twists",
        name: "Luminous Senegalese Twists",
        description: "Even rope twists with a warm, dimensional finish.",
        category: "twists",
        serviceId: "svc-twists",
        image: "/images/style-twists.jpg",
        durationMin: 300,
        durationMax: 420,
        priceFrom: 230,
        featured: true,
      },
      {
        id: "stl-fulani-gold",
        slug: "fulani-gold",
        name: "Fulani Gold",
        description: "Center-part Fulani braids with antique gold beads.",
        category: "special",
        serviceId: "svc-fulani",
        image: "/images/style-fulani.jpg",
        durationMin: 300,
        durationMax: 390,
        priceFrom: 260,
        featured: true,
      },
      {
        id: "stl-goddess-boho",
        slug: "goddess-boho",
        name: "Goddess Boho",
        description: "Knotless goddess braids with human-hair curl ends.",
        category: "special",
        serviceId: "svc-goddess",
        image: "/images/style-goddess.jpg",
        durationMin: 360,
        durationMax: 480,
        priceFrom: 310,
        featured: true,
      },
      {
        id: "stl-kids-beads",
        slug: "kids-beaded-braids",
        name: "Kids Beaded Braids",
        description: "Gentle kids braids finished with colorful beads.",
        category: "kids",
        serviceId: "svc-kids",
        image: "/images/style-kids.jpg",
        durationMin: 120,
        durationMax: 210,
        priceFrom: 110,
        featured: true,
      },
      {
        id: "stl-lemonade",
        slug: "lemonade-braids",
        name: "Lemonade Braids",
        description: "Side-swept layered cornrows with a red-carpet finish.",
        category: "cornrows",
        serviceId: "svc-cornrows",
        image: "/images/gallery-04.jpg",
        durationMin: 180,
        durationMax: 270,
        priceFrom: 165,
        featured: true,
      },
      {
        id: "stl-tribal",
        slug: "ceremonial-tribal",
        name: "Ceremonial Tribal",
        description: "Sculpted tribal braids for weddings and special days.",
        category: "special",
        serviceId: "svc-fulani",
        image: "/images/gallery-05.jpg",
        durationMin: 240,
        durationMax: 360,
        priceFrom: 240,
        featured: true,
      },
    ],
    stylists: [
      {
        id: "sty-angel",
        slug: "angel-mensah",
        name: "Angel Mensah",
        role: "Founder & Master Stylist",
        bio: "Raised between Accra and Columbus, Angel built the salon as a house of African craft and modern luxury. Two decades of braiding, one uncompromising standard.",
        image: "/images/stylist-angel.jpg",
        specialties: [
          "svc-knotless",
          "svc-goddess",
          "svc-fulani",
          "svc-box-braids",
          "svc-twists",
          "svc-cornrows",
          "svc-kids",
          "svc-extensions",
          "svc-wig",
          "svc-natural",
        ],
        workingDays: [0, 2, 3, 4, 5, 6],
        startHour: 9,
        endHour: 19,
      },
      {
        id: "sty-nia",
        slug: "nia-okonkwo",
        name: "Nia Okonkwo",
        role: "Knotless Specialist",
        bio: "Nia’s knotless work is known for invisible starts and hairline kindness. She designs small and medium sets that last without sacrificing comfort.",
        image: "/images/stylist-nia.jpg",
        specialties: [
          "svc-knotless",
          "svc-goddess",
          "svc-box-braids",
          "svc-extensions",
          "svc-natural",
        ],
        workingDays: [2, 3, 4, 5, 6],
        startHour: 9,
        endHour: 19,
      },
      {
        id: "sty-amina",
        slug: "amina-diallo",
        name: "Amina Diallo",
        role: "Twists & Fulani Artist",
        bio: "From Dakar’s braiding houses to Columbus, Amina brings ceremonial detail to twists, Fulani, and special-occasion silhouettes.",
        image: "/images/stylist-amina.jpg",
        specialties: [
          "svc-twists",
          "svc-fulani",
          "svc-box-braids",
          "svc-cornrows",
          "svc-extensions",
        ],
        workingDays: [0, 2, 3, 5, 6],
        startHour: 10,
        endHour: 18,
      },
      {
        id: "sty-keisha",
        slug: "keisha-brooks",
        name: "Keisha Brooks",
        role: "Kids & Cornrow Artist",
        bio: "Keisha makes the chair feel safe — especially for children — and her feed-in cornrows are some of the cleanest in the city.",
        image: "/images/stylist-keisha.jpg",
        specialties: [
          "svc-kids",
          "svc-cornrows",
          "svc-box-braids",
          "svc-wig",
          "svc-natural",
        ],
        workingDays: [2, 3, 4, 5, 6],
        startHour: 9,
        endHour: 17,
      },
    ],
    gallery: [
      {
        id: "gal-01",
        title: "Honey Box Braids",
        description: "Dimensional honey-brown medium box braids, hip length.",
        image: "/images/gallery-01.jpg",
        category: "braids",
        styleId: "stl-classic-box",
        serviceId: "svc-box-braids",
        durationLabel: "5–7 hr",
        priceFrom: 220,
      },
      {
        id: "gal-02",
        title: "Jumbo Knotless Profile",
        description: "Sculptural jumbo knotless with a fashion-week silhouette.",
        image: "/images/gallery-02.jpg",
        category: "knotless",
        styleId: "stl-jumbo-knotless",
        serviceId: "svc-knotless",
        durationLabel: "4–6 hr",
        priceFrom: 200,
      },
      {
        id: "gal-03",
        title: "Mapped Cornrows",
        description: "Close-up of a geometric cornrow pattern, precision parted.",
        image: "/images/gallery-03.jpg",
        category: "cornrows",
        styleId: "stl-designer-cornrows",
        serviceId: "svc-cornrows",
        durationLabel: "2.5–4 hr",
        priceFrom: 140,
      },
      {
        id: "gal-04",
        title: "Lemonade at Golden Hour",
        description: "Side-part lemonade braids with a luminous finish.",
        image: "/images/gallery-04.jpg",
        category: "cornrows",
        styleId: "stl-lemonade",
        serviceId: "svc-cornrows",
        durationLabel: "3–4.5 hr",
        priceFrom: 165,
      },
      {
        id: "gal-05",
        title: "Ceremonial Tribal",
        description: "Special-occasion tribal braids with gold adornment.",
        image: "/images/gallery-05.jpg",
        category: "special",
        styleId: "stl-tribal",
        serviceId: "svc-fulani",
        durationLabel: "4–6 hr",
        priceFrom: 240,
      },
      {
        id: "gal-06",
        title: "Fulani Gold Detail",
        description: "Antique gold beads and cowrie accents on Fulani braids.",
        image: "/images/gallery-06.jpg",
        category: "special",
        styleId: "stl-fulani-gold",
        serviceId: "svc-fulani",
        durationLabel: "5–6.5 hr",
        priceFrom: 260,
      },
      {
        id: "gal-07",
        title: "Little Crown",
        description: "Kids cornrows with gold beads, styled with patience.",
        image: "/images/gallery-07.jpg",
        category: "kids",
        styleId: "stl-kids-beads",
        serviceId: "svc-kids",
        durationLabel: "2–3.5 hr",
        priceFrom: 110,
      },
      {
        id: "gal-08",
        title: "Waist-Length Walk",
        description: "A cascade of long braids — movement as luxury.",
        image: "/images/gallery-08.jpg",
        category: "braids",
        styleId: "stl-classic-box",
        serviceId: "svc-box-braids",
        durationLabel: "6–8 hr",
        priceFrom: 280,
      },
      {
        id: "gal-09",
        title: "Small Knotless",
        description: "Fine knotless braids with a seamless, weightless root.",
        image: "/images/style-knotless.jpg",
        category: "knotless",
        styleId: "stl-small-knotless",
        serviceId: "svc-knotless",
        durationLabel: "7–9 hr",
        priceFrom: 320,
      },
      {
        id: "gal-10",
        title: "Goddess Boho",
        description: "Romantic goddess braids with soft human-hair curls.",
        image: "/images/style-goddess.jpg",
        category: "special",
        styleId: "stl-goddess-boho",
        serviceId: "svc-goddess",
        durationLabel: "6–8 hr",
        priceFrom: 310,
      },
      {
        id: "gal-11",
        title: "Senegalese Light",
        description: "Luminous twists with a warm, dimensional brown.",
        image: "/images/style-twists.jpg",
        category: "twists",
        styleId: "stl-senegalese",
        serviceId: "svc-twists",
        durationLabel: "5–7 hr",
        priceFrom: 230,
      },
      {
        id: "gal-12",
        title: "Kids Beads",
        description: "Playful, gentle kids braids ready for the week.",
        image: "/images/style-kids.jpg",
        category: "kids",
        styleId: "stl-kids-beads",
        serviceId: "svc-kids",
        durationLabel: "2–3.5 hr",
        priceFrom: 110,
      },
    ],
    testimonials: [
      {
        id: "t-maya",
        name: "Maya Johnson",
        image: "/images/client-maya.jpg",
        rating: 5,
        quote:
          "I have never left a braiding chair feeling this taken care of. The knotless set is light, the parts are immaculate, and the salon feels like a private atelier.",
        service: "Small Knotless Braids",
      },
      {
        id: "t-zara",
        name: "Zara Boateng",
        image: "/images/client-zara.jpg",
        rating: 5,
        quote:
          "Angel understood the look I wanted before I finished the sentence. My goddess braids lasted eight weeks and still looked editorial.",
        service: "Goddess Braids",
      },
      {
        id: "t-amara",
        name: "Amara Cole",
        image: "/images/client-amara.jpg",
        rating: 5,
        quote:
          "The cornrows are art. Precise, comfortable, and finished with a level of care I have not found anywhere else in Columbus.",
        service: "Designer Cornrows",
      },
      {
        id: "t-lina",
        name: "Lina Mensah",
        image: "/images/client-lina.jpg",
        rating: 5,
        quote:
          "From the booking to the chair, everything felt premium. My twists are glossy, even, and exactly the color we discussed.",
        service: "Senegalese Twists",
      },
    ],
    appointments: [
      {
        id: "apt-1001",
        reference: "ANG-4F21",
        serviceId: "svc-knotless",
        styleId: "stl-small-knotless",
        stylistId: "sty-nia",
        date: dateOffset(0),
        time: "09:00",
        durationMin: 420,
        price: 320,
        status: "confirmed",
        customerName: "Maya Johnson",
        customerPhone: "(404) 555-0192",
        customerEmail: "maya.johnson@email.com",
        notes: "Honey brown, hip length, extra small.",
        deposit: { required: true, amount: 50, status: "paid" },
        createdAt: daysAgo(12),
        updatedAt: daysAgo(2),
      },
      {
        id: "apt-1002",
        reference: "ANG-8C90",
        serviceId: "svc-kids",
        styleId: "stl-kids-beads",
        stylistId: "sty-keisha",
        date: dateOffset(0),
        time: "13:00",
        durationMin: 150,
        price: 120,
        status: "in_progress",
        customerName: "Priya Walsh",
        customerPhone: "(678) 555-0144",
        customerEmail: "priya.walsh@email.com",
        notes: "Daughter, age 8. Gold beads.",
        deposit: { required: true, amount: 30, status: "paid" },
        createdAt: daysAgo(6),
        updatedAt: daysAgo(0),
      },
      {
        id: "apt-1003",
        reference: "ANG-2A17",
        serviceId: "svc-goddess",
        styleId: "stl-goddess-boho",
        stylistId: "sty-angel",
        date: dateOffset(1),
        time: "10:00",
        durationMin: 420,
        price: 340,
        status: "pending",
        customerName: "Zara Boateng",
        customerPhone: "(470) 555-0118",
        customerEmail: "zara.boateng@email.com",
        notes: "Boho curls, waist length.",
        deposit: { required: true, amount: 50, status: "unpaid" },
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
      },
      {
        id: "apt-1004",
        reference: "ANG-7D33",
        serviceId: "svc-twists",
        styleId: "stl-senegalese",
        stylistId: "sty-amina",
        date: dateOffset(3),
        time: "11:00",
        durationMin: 360,
        price: 240,
        status: "confirmed",
        customerName: "Lina Mensah",
        customerPhone: "(404) 555-0177",
        customerEmail: "lina.mensah@email.com",
        notes: "",
        deposit: { required: true, amount: 50, status: "paid" },
        createdAt: daysAgo(8),
        updatedAt: daysAgo(3),
      },
      {
        id: "apt-1005",
        reference: "ANG-1B08",
        serviceId: "svc-cornrows",
        styleId: "stl-designer-cornrows",
        stylistId: "sty-keisha",
        date: dateOffset(-12),
        time: "10:00",
        durationMin: 180,
        price: 150,
        status: "completed",
        customerName: "Amara Cole",
        customerPhone: "(770) 555-0160",
        customerEmail: "amara.cole@email.com",
        notes: "",
        deposit: { required: true, amount: 30, status: "paid" },
        createdAt: daysAgo(20),
        updatedAt: daysAgo(12),
      },
      {
        id: "apt-1006",
        reference: "ANG-9E44",
        serviceId: "svc-box-braids",
        styleId: "stl-classic-box",
        stylistId: "sty-angel",
        date: dateOffset(-20),
        time: "09:00",
        durationMin: 360,
        price: 260,
        status: "completed",
        customerName: "Maya Johnson",
        customerPhone: "(404) 555-0192",
        customerEmail: "maya.johnson@email.com",
        notes: "",
        deposit: { required: true, amount: 50, status: "paid" },
        createdAt: daysAgo(28),
        updatedAt: daysAgo(20),
      },
      {
        id: "apt-1007",
        reference: "ANG-5F12",
        serviceId: "svc-fulani",
        styleId: "stl-fulani-gold",
        stylistId: "sty-amina",
        date: dateOffset(-5),
        time: "10:00",
        durationMin: 330,
        price: 270,
        status: "cancelled",
        customerName: "Imani Grant",
        customerPhone: "(404) 555-0133",
        customerEmail: "imani.grant@email.com",
        notes: "Rescheduling next month.",
        deposit: { required: true, amount: 50, status: "waived" },
        createdAt: daysAgo(9),
        updatedAt: daysAgo(5),
      },
    ],
    customers: [
      {
        id: "cus-maya",
        name: "Maya Johnson",
        email: "maya.johnson@email.com",
        phone: "(404) 555-0192",
        favoriteStyleIds: ["stl-small-knotless", "stl-classic-box"],
        createdAt: daysAgo(400),
      },
      {
        id: "cus-zara",
        name: "Zara Boateng",
        email: "zara.boateng@email.com",
        phone: "(470) 555-0118",
        favoriteStyleIds: ["stl-goddess-boho"],
        createdAt: daysAgo(210),
      },
      {
        id: "cus-amara",
        name: "Amara Cole",
        email: "amara.cole@email.com",
        phone: "(770) 555-0160",
        favoriteStyleIds: ["stl-designer-cornrows"],
        createdAt: daysAgo(180),
      },
      {
        id: "cus-lina",
        name: "Lina Mensah",
        email: "lina.mensah@email.com",
        phone: "(404) 555-0177",
        favoriteStyleIds: ["stl-senegalese"],
        createdAt: daysAgo(90),
      },
      {
        id: "cus-priya",
        name: "Priya Walsh",
        email: "priya.walsh@email.com",
        phone: "(678) 555-0144",
        favoriteStyleIds: ["stl-kids-beads"],
        createdAt: daysAgo(40),
      },
    ],
    emails: [],
  };
}
